package:
  name: sidescantools
  version: 1.0.2

source:
  path: ..

build:
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.12,<=3.13.*
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.12,<=3.13.*
    - conda-forge::pydantic
    - scikit-image==0.25.2
    - geopy
    - numpy==2.3.3
    - pillow
    - conda-forge::napari
    - conda-forge::pyqt==5.*
    - conda-forge::gdal==3.10.3
    - pyyaml
    - qtpy
    - pyproj
    - pygmt==0.17.0
    - rioxarray==0.18.1
    - rasterio==1.4.3
    - scipy
    - pyqtgraph
    - conda-forge::utm
    - conda-forge::pyxtf==1.4.2

test:
  imports:
    - sidescantools

about:
  home: https://github.com/StrikeLines/StrikeLines-SonarSuite
  summary: "SonarSuite - fast, standalone sidescan sonar processing"
  license: GPL-3.0

extra:
  recipe-maintainers:
    - StrikeLines
